# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

def main_pods
  pod 'Realm'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]
end

def testing_pods
  pod 'Realm/Headers'
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end


target 'ReactNativeWithPods' do main_pods end;
target 'ReactNativeWithPodsTests' do testing_pods end;
target 'ReactNativeWithPodsUITests' do testing_pods end;