# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'ReactNativeWithPods' do
  pod 'Realm'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]
end

target 'ReactNativeWithPodsTests' do
  pod 'Realm/Headers'
end

target 'ReactNativeWithPodsUITests' do

end

